# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "275"
  name: "ibm-b2bi-psp"
  labels:
    app: "ibm-b2bi-psp"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ibm-b2bi-psp"
subjects:
- kind: ServiceAccount
  name: b2bi
  namespace: b2bi-prod
