kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  name: 'system:openshift:scc:anyuid'
  namespace: cp4ba
subjects:
  - kind: ServiceAccount
    name: ibm-cp4ba-anyuid
    namespace: cp4ba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
