kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  name: minio-dev-resources
  # labels:
  #   app.kubernetes.io/component: resources
  #   app.kubernetes.io/instance: ibm-sfg-b2bi
  #   app.kubernetes.io/managed-by: Helm
  #   app.kubernetes.io/name: sfg
  #   helm.sh/chart: ibm-sfg-prod
  #   release: ibm-sfg-b2bi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
