kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odm-postdeploy-rolebinding
subjects:
  - kind: ServiceAccount
    name: odm-postdeploy-sa
    namespace: cp4ba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odm-postdeploy-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
subjects:
  - kind: ServiceAccount
    name: odm-postdeploy-sa
    namespace: cp4ba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
