kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault-ui
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "295"
spec:
  host: vault-ui-default.apps-crc.testing
  path: /
  to:
    kind: Service
    name: vault
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None