kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "250"
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
 #storageClassName: ""
  volumeMode: Filesystem