apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault01-agent-injector-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "220"
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault01
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs:
    - "get"
    - "list"
    - "watch"
    - "patch"

