apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "225"
  namespace: ssp
  name: keycert-hook-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete