apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycert-job-role
  namespace: {{ .Values.namespace | quote }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - secrets
    verbs:
      - get
      - watch
      - list
      - create
