apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "ibm-ssp-cm" "persistentVolume" "existingClaimName" | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ index .Values "ibm-ssp-cm" "persistentVolume" "storageClassName" | quote }}
  volumeMode: Filesystem
