apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: "ibm-ssp-cm-scc"
  labels:
    app: "ibm-ssp-cm-scc"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ibm-ssp-cm-scc"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: {{ .Values.namespace | quote }}