{{- include "sch.config.init" (list . "ibm-ssp-cm.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-ssp-cm.chart" .  }}
    release: {{  .Release.Name  }}
    namespace: {{ .Release.Namespace }}
    
imagePullSecrets:
  - name: ibm-entitlement-key
  {{- if  .Values.image.imageSecrets }}
  - name: {{ .Values.image.imageSecrets }}
  {{- end }}
{{- end }}
