apiVersion: v1
kind: Service
metadata:
  name: vault01-agent-injector-svc
  annotations:
    argocd.argoproj.io/sync-wave: "290"
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault01
    app.kubernetes.io/managed-by: Helm
  
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault01
    component: webhook