{{ include "sch.config.init" (list . "ibm-ssp-engine.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list . "podRoleBind") }}
{{ $fullName := include "sch.names.fullName" (list . "podRoleBind") }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sch.names.fullCompName" (list . "podRoleBind") | quote }}
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-ssp-engine.chart" .  }}
    release: {{  .Release.Name  }}
 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sch.names.fullCompName" (list . "podClusterRole") }}
subjects:
 - kind: ServiceAccount
   name: {{ $saName }}
   namespace: {{ .Release.Namespace }}
{{- end }}

