apiVersion: v1
kind: Secret
metadata:
  name: ibm-ssp-cm-secret
type: Opaque
data:
  sysPassphrase: UGFzc3dvcmRAMTIz
  adminPassword: UGFzc3dvcmRAMTIz
  keyCertStorePassphrase: cGFzc3dvcmQ=
  keyCertEncryptPassphrase: cGFzc3dvcmQ=
  customKeyCertPassphrase: cGFzc3dvcmQ=