apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cd-63-ibm-connect-direct
  labels:
    app.kubernetes.io/name: ibm-connect-direct
    app.kubernetes.io/instance: cd-63
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: ibm-connect-direct-1.3.0
    release: cd-63
    author: IBM
  namespace: scd
  annotations:
    argocd.argoproj.io/sync-wave: "250"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-connect-direct
      app.kubernetes.io/instance: cd-63
      author: IBM
  serviceName: cd-63-ibm-connect-direct
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-connect-direct
        app.kubernetes.io/instance: cd-63
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: ibm-connect-direct-1.3.0
        release: cd-63
        author: IBM
      annotations:
        license: "true"        
        productID: "0e99fe73c7ae4b799e11d00a9bbf0db0"
        productName: "IBM Sterling Connect Direct Premium Ed Certified Container"
        productVersion: "6.3"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
        checksum/config: 80b9b979da2ffb9befc945d0fd52bb459298068f14b2be3ee747e8f6d7dc3a60
    spec:
      serviceAccountName: cd-63-ibm-connect-direct-serviceaccount
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext: 
        
        fsGroup: 45678
        runAsGroup: 45678
        runAsNonRoot: true
        runAsUser: 45678
        supplementalGroups:
        - 65534
      affinity:        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:      
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution: 
      containers:
        - name: cd-63-ibm-connect-direct
          image: "cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.2:6.3.0.2_ifix009"
          imagePullPolicy: IfNotPresent
          env:
            - name: CD_License_Acceptance
              value: "true"
            - name: TZ
              value: UTC
            # LDAP configuration
            - name: SACL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: cd-63-ibm-connect-direct
                  key: saclConfig
            - name: CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: cd-63-ibm-connect-direct
                  resource: requests.cpu
            - name: LICENSE_TYPE
              value: "prod"
          ports:
          # Map the configuration directory from inside the container to the
          # persistent volume claims
          volumeMounts:
            - mountPath: /opt/cdunix/ndm/cfg
              name: cd-vol
              subPath: CFG
            - mountPath: /opt/cdunix/work
              name: cd-vol
              subPath: WORK
            - mountPath: /opt/cdunix/ndm/secure+
              name: cd-vol
              subPath: SECPLUS
            - mountPath: /opt/cdunix/ndm/security
              name: cd-vol
              subPath: SECURITY
            - mountPath: /opt/cdunix/process
              name: cd-vol
              subPath: PROCESS
          # File agent support on container
            - mountPath: /opt/cdunix/file_agent/config
              name: cd-vol
              subPath: FACONFIG
            - mountPath: /opt/cdunix/file_agent/log
              name: cd-vol
              subPath: FALOG
          # CD Configurations using dynamic or non-dynamic prov
            - mountPath: /opt/cdfiles/cdcert 
              name: cd-cert-secret
              readOnly: true 
            - mountPath: /opt/cdfiles/cd_param_file
              name: cd-param
              subPath: cd_param_file
              readOnly: true
            - mountPath: /opt/cdfiles/secret_files
              name: cd-secret
              readOnly: true
# Extra Volume Mounts
            - mountPath: /opt/backup
              name: cd-vol
              subPath: BACKUP

          # Add the required linux capabilities
          securityContext:
            
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - SETGID
              - SETUID
              - DAC_OVERRIDE
              - AUDIT_WRITE
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 45678

          # Set startup probe to determine if Connect Direct has completed startup procedure
          startupProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            exec:
              command:
              - /bin/sh
              - -c
              - /cdinstall/cdmonitor.sh 1363
          # Set liveness probe to determine if Connect Direct is running
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            exec:
              command:
              - /bin/sh
              - -c
              - /cdinstall/cdmonitor.sh 1363
          # Set readiness probe to determine if Connect Direct is running
          readinessProbe: 
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            exec:
              command:
              - /bin/sh
              - -c
              - /cdinstall/cdmonitor.sh 1363
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 5Gi
              memory: 2000Mi
            requests:
              cpu: 500m
              ephemeral-storage: 3Gi
              memory: 2000Mi
          
      # Create a volume which will be used while creating the container.
      # The volume claim needs to be created before using this volume.
      volumes:
      - name: cd-vol
        persistentVolumeClaim:
          claimName: cd-63-ibm-connect-direct-pvc
      - name: cd-param 
        configMap:
          name: cd-63-ibm-connect-direct
          defaultMode: 292
      - name: cd-secret
        secret: 
          secretName: cd-secret
          defaultMode: 292
      - name: cd-cert-secret
        secret:
          secretName: cd-cert-secret
          defaultMode: 292
# Extra Volumes
